### ISSUE TITLE
Does the dyantrace support for java-native-image?

### ISSUE THREAD

**Issue by zhoufenqin** [paketo-buildpacks/dynatrace#16]
From [java-native-image](https://github.com/paketo-buildpacks/java-native-image), I didn't see the dependency dynatrace buildpack, But if I put [tanzu-java-azure](https://github.com/pivotal-cf/tanzu-java-azure) buildpack in the same group with java-native-image in a builder, then the dynatrace can be picked up.

I see the dynatrace support GraalVM from [1.201](https://www.dynatrace.com/support/help/whats-new/release-notes/oneagent/sprint-201), but it doesn't work in java-native-image buildpacks

![image](https://user-images.githubusercontent.com/8765864/195529241-96b2ecf1-89e9-4d55-b6d6-c2cd342da3eb.png)

Do you need to do somthing to support dynatrace in java-native-image buildpacks or is it a bug?

## Steps to Reproduce

1.

**Comment by dmikusa** [comment]
>From [java-native-image](https://github.com/paketo-buildpacks/java-native-image), I didn't see the dependency dynatrace buildpack

We do not presently have any of the Paketo APM buildpacks included with the Java composite buildpacks (java, java-azure and java-native-image). This is due to technical reasons that are presently outside our control. We'll hopefully be able to workaround these limitations in the future and we can add all the buildpacks to the builders. For now, you just need to bring your own APM buildpack by using the `pack build -b` flag. See https://paketo.io/docs/howto/app-monitor/#apm-buildpacks-with-paketo-builders, which also explains the limitation as well.
